FROM node:20
WORKDIR /app

COPY package.json ./

RUN npm install


# Declarar los args
ARG REACT_APP_DEVMART_API
ARG REACT_APP_USERS_API
ARG REACT_APP_NOTIFICATIONS_API

# Convertirlos en ENV para que React los tome en el build
ENV REACT_APP_DEVMART_API=$REACT_APP_DEVMART_API
ENV REACT_APP_USERS_API=$REACT_APP_USERS_API
ENV REACT_APP_NOTIFICATIONS_API=$REACT_APP_NOTIFICATIONS_API
ENV PORT=5173 

COPY . .


EXPOSE 5173

CMD ["npm","start"]