FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci

ARG REACT_APP_DEVMART_API
ARG REACT_APP_USERS_API
ARG REACT_APP_NOTIFICATIONS_API
ARG REACT_APP_SOCKET_SERVER_URL

ENV REACT_APP_DEVMART_API=$REACT_APP_DEVMART_API
ENV REACT_APP_USERS_API=$REACT_APP_USERS_API
ENV REACT_APP_NOTIFICATIONS_API=$REACT_APP_NOTIFICATIONS_API
ENV REACT_APP_SOCKET_SERVER_URL=$REACT_APP_SOCKET_SERVER_URL

COPY . .

RUN npm run build

FROM nginx:alpine


COPY nginx.conf /etc/nginx/nginx.conf

COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]