FROM node:20
WORKDIR /app

COPY package.json ./

RUN npm install

COPY . .

ARG REACT_APP_DEVMART_API
ARG REACT_APP_USERS_API
ARG REACT_APP_NOTIFICATIONS_API

ENV REACT_APP_DEVMART_API=$REACT_APP_DEVMART_API
ENV REACT_APP_USERS_API=$REACT_APP_USERS_API
ENV REACT_APP_NOTIFICATIONS_API=$REACT_APP_NOTIFICATIONS_API

EXPOSE 5173

CMD ["npm","start"]